-- Rainbow Rampage leaderboard table
-- Run this in Supabase SQL Editor

create table if not exists public.rainbow_rampage_scores (
  id bigint generated by default as identity primary key,
  player_name text not null,
  score integer not null default 0,
  distance integer not null default 0,
  character text not null default 'unknown',
  created_at timestamptz not null default now()
);

create index if not exists rainbow_rampage_scores_rank_idx
on public.rainbow_rampage_scores (score desc, distance desc, created_at asc);

-- Optional: stop public direct table access.
-- The game uses Vercel API routes with your server-side service role key.
alter table public.rainbow_rampage_scores enable row level security;
